language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - CXX11=True
  - CXX11=False

matrix:
  exclude:
    - os: linux
      compiler: gcc
      env: CXX11=True
    - os: linux
      compiler: clang
      env: CXX11=False
    - os: osx
      compiler: gcc
      env: CXX11=False
    - os: osx
      compiler: clang
      env: CXX11=True

sudo: false

install:
  - ./travis-deps.sh

addons:
  apt:
    packages:
    - cmake
    - flex
    - bison
    - libblas-dev
    - liblapack-dev
    - libcfitsio3-dev
    - wcslib-dev
    - libfftw3-dev
    - gfortran
    - libncurses5-dev
    - libreadline6-dev
    - libhdf5-serial-dev
    - libboost-dev
    - libboost-python-dev
    - python-numpy

before_script:
  - wget http://www.iausofa.org/2015_0209_F/sofa_f-20150209_a.tar.gz -O /tmp/sofa.tgz
  - tar -xzf /tmp/sofa.tgz
  - cd sofa/20150209_a/f77/src/ && make && make test && cd ../../../../
  - mkdir build
  - cd build
  - wget ftp://ftp.astron.nl/outgoing/Measures/WSRT_Measures.ztar
  - tar zxvf WSRT_Measures.ztar
  - cmake ..
      -DUSE_FFTW3=ON
      -DBUILD_TESTING=ON
      -DUSE_OPENMP=OFF
      -DUSE_HDF5=ON
      -DBUILD_PYTHON=ON
      -DDATA_DIR=$PWD
      -DSOFA_ROOT_DIR=$HOME
      -DCXX11=$CXX11
      -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/installed

script:
  - make -j4 
  - make test
  - make install

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a21dbde2d416245fd698
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
