#!/bin/sh
#-----------------------------------------------------------------------------
# Script to test the TableGram and TableParse class.  All files generated will
# be deleted on exit.
#=============================================================================

# Create a symlink to achieve that casacore_memcheck (if used) will use
# that name 
rm -f tTableGramAlttab
ln -s tTableGram tTableGramAlttab


# Execute all kind of table creation commands.
# Check the result using showtable (leave out version line and path).
curdir=`pwd`

# First create the tables to use.
echo ""
$casa_checktool ./tTableGram 'create table tTableGramAlttab_tmp.tab2 (col1 i4 [shape=[2,3], unit="m"], col2 B) dminfo [TYPE="IncrementalStMan",NAME="ISM1",SPEC=[BUCKETSIZE=16384],COLUMNS=["col1"]]'
$casa_checktool ./tTableGram 'create table tTableGramAlttab_tmp.tab2/subtab'
../../apps/showtable in=tTableGramAlttab_tmp.tab2 | grep -v 'showtable:' | sed -e "s%$curdir/%%"
$casa_checktool ./tTableGram 'alter table tTableGramAlttab_tmp.tab2/subtab ADD COLUMN colxyz S SET KEYWORD colxyz::skey="newval"'
../../apps/showtable in=tTableGramAlttab_tmp.tab2/subtab colkey=T | grep -v 'showtable:' | sed -e "s%$curdir/%%"

echo ""
$casa_checktool ./tTableGram 'alter table tTableGramAlttab_tmp.tab2 SET KEYWORD subtab="Table: tTableGramAlttab_tmp.tab2/subtab", ::key1=3, col1::subrec=[=], col1::subrec.k1="3x"'
../../apps/showtable in=tTableGramAlttab_tmp.tab2 tabkey=T colkey=T | grep -v 'showtable:' | sed -e "s%$curdir/%%"

echo ""
$casa_checktool ./tTableGram 'alter table tTableGramAlttab_tmp.tab2 FROM ::subtab t1 SET KEYWORD col1::subrec.k1 AS t1.colxyz::skey, RENAME KEYWORDS key1 TO key1n DROp keyword subtab'
../../apps/showtable in=tTableGramAlttab_tmp.tab2 tabkey=T colkey=T | grep -v 'showtable:' | sed -e "s%$curdir/%%"

echo ""
$casa_checktool ./tTableGram 'alter table tTableGramAlttab_tmp.tab2 ADD COLUMN col1a i4 [shape=[2,3], unit="m", dmtype="IncrementalStMan"], col2a B'
../../apps/showtable in=tTableGramAlttab_tmp.tab2 | grep -v 'showtable:' | sed -e "s%$curdir/%%"

echo ""
$casa_checktool ./tTableGram 'alter table tTableGramAlttab_tmp.tab2 RENAME COLUMN col1a to col1b, col2a to col2b'
../../apps/showtable in=tTableGramAlttab_tmp.tab2 | grep -v 'showtable:' | sed -e "s%$curdir/%%"

$casa_checktool ./tTableGram 'alter table tTableGramAlttab_tmp.tab2 DROP COLUMN col1b,col2 ,ADDrows 4 +5'
../../apps/showtable in=tTableGramAlttab_tmp.tab2 | grep -v 'showtable:' | sed -e "s%$curdir/%%"
 
exit 0
