#!/bin/sh
#-----------------------------------------------------------------------------
# Script to test the masked array in TableGram and TableParse.
# All files generated will be deleted on exit.
#=============================================================================

# Create a symlink to achieve that casacore_memcheck (if used) will use
# that name 
rm -f tTableGramMasked
ln -s tTableGram tTableGramMasked

# Set default testsrcdir if undefined.
if test "$testsrcdir" = ""; then
  testsrcdir=../../../../../casacore/tables/TaQL/test
fi

# Use table tTable_2.data_v0 as the input by copying it.
rm -rf tTableGramMasked_tmp.tab*
mkdir tTableGramMasked_tmp.tab
cp -r $testsrcdir/../../Tables/test/tTable_2.data_v0/table.* tTableGramMasked_tmp.tab
chmod 644 tTableGramMasked_tmp.tab/*


$casa_checktool ./tTableGramMasked 'select sum(arr1),sum(arr1[arr1%3>0]),sum(arr1[arr1%3==0]) from tTableGramMasked_tmp.tab'

$casa_checktool ./tTableGramMasked 'select sum(arraydata(replacemasked(arr1[arr1%3>0], 1))) from tTableGramMasked_tmp.tab'

$casa_checktool ./tTableGramMasked 'select sum(arraydata(replaceunmasked(arr1[arr1%3>0], 1))) from tTableGramMasked_tmp.tab'

exit 0
